name: Readme Fetch
description: Generate readme with readme-fetch
on:
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ssiyad/readme-fetch@master
        with:
          git_user: ssiyad
          git_email: hello@ssiyad.com
