name: Readme Fetch
description: Generate readme with readme-fetch
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ssiyad/readme-fetch@master
        with:
          user: ssiyad
          host: baghdad
          birthday: 1998-03-28
          git_user: ssiyad
          git_email: hello@ssiyad.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
